CREATE TABLE SCHOOL (
  SCHOOL_ID INT  GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  SCHOOL_NUMBER INT NOT NULL,
  SCHOOL_NAME VARCHAR(128)  NOT NULL);

CREATE TABLE BATCH (
  BATCH_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  BATCH_NUMBER VARCHAR(45)  NOT NULL,
  BATCH_SCHOOL_ID INT NOT NULL,
  CONSTRAINT fk_BATCH_SCHOOL1
    FOREIGN KEY (BATCH_SCHOOL_ID)
    REFERENCES SCHOOL (SCHOOL_ID));

CREATE TABLE STUDENT (
  STUD_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY ,
  STUD_FNAME VARCHAR(128)  NOT NULL,
  STUD_LNAME VARCHAR(128)  NOT NULL,
  STUD_PNAME VARCHAR(128)  NOT NULL,
  STUD_NUM_ZACH VARCHAR(45)  NOT NULL,
  STUD_BATCH_ID INT NOT NULL,
  CONSTRAINT fk_STUDENT_BATCH
    FOREIGN KEY (STUD_BATCH_ID)
    REFERENCES BATCH (BATCH_ID));
